# Apply once:  kubectl apply -f argocd/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rahul-portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rahuldan98/rahul-portfolio.git   # TODO: your Git repo
    targetRevision: main
    path: k8s                                                    # folder with kustomization.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
