apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rahuldan98/rahul-portfolio-latest
    newName: rahuldan98/rahul-portfolio-latest   # TODO: your Docker Hub user
    newTag: "3650019c2b923e6a8ac0684f59b36c39606bb961"
