apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rahuldan98/rahul-portfolio-latest
    newName: rahuldan98/rahul-portfolio-latest   # TODO: your Docker Hub user
    newTag: "5077f60f95bf729f73a6eb0bf0338834c06f8970"
