apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rahuldan98/rahul-portfolio-latest
    newName: rahuldan98/rahul-portfolio-latest   # TODO: your Docker Hub user
    newTag: "8300baa7cddaa46cbfd0aa2f4c2c0d6f620a16ac"
